### ISSUE TITLE
[inference code error] Could not convert bvh file from predict data

### ISSUE THREAD

**Issue by habakan** [rubenvillegas/cvpr2018nkn#1]
I try to inference test data after training NKN with Adversarial Cycle Consistency.
Training data was downloaded from mixamo site, and converted to npy file using datasets/fbx2bvh.py and datasets/preprocess.py.

run command
```
CUDA_VISIBLE_DEVICES=0 python src/test_online_retargeting_mixamo.py --gpu=0 --prefix=Online_Retargeting_Mixamo_Cycle_Adv_beta\=0.001_gru_units\=512_optim\=adam_d_arch\=2_learning_rate\=0.0001_omega\=0.01_norm_type\=batch_norm_d_rand\=True_num_layer\=2_alpha\=100.0_euler_ord\=yzx_margin\=0.3_keep_prob\=0.9_gamma\=10.0
```

But I got this error.

output error code
```
[*] Reading checkpoints...
     Loaded model: EncoderDecoderGRU.model-50094
[*] Load SUCCESS
Testing: 0/185
Traceback (most recent call last):
  File "src/test_online_retargeting_mixamo.py", line 240, in <module>
    main(**vars(args))
  File "src/test_online_retargeting_mixamo.py", line 139, in main
    -4] = localA_batch[:, :step, :-4] * local_std + local_mean
ValueError: operands could not be broadcast together with shapes (1,120,62) (1,1,66)
```

I downloaded test data using datasets/download_test.sh.
These shapes of the test data loaded npy file is (120, 66).
I think this code intended shape of the test data is (120, 70), but this data seems not to include root_x, y, z, and root_r.
Is there any way to resolve this problem?
Thank you.

## Environments
* Python 2.7.12

**Comment by rubenvillegas** [comment]
Sorry about that. I changed the variable names at some point to make it consistent with the paper. I believe all the localA_batch from that line and below should be seqA_batch. Can you please try that and change that, and let me know if it works?

**Comment by habakan** [comment]
I try to replace seqA_batch from localA_batch, it successfully works.
I sent pull request about commit of this change code.
