### ISSUE TITLE
Issue about the test data.

### ISSUE THREAD

**Issue by layewong1207** [rubenvillegas/cvpr2018nkn#10]
Sorry for the issue.
We are studying this project, and we are trying to use data other than Mixamo.
During testing, we found that there are three npy files for each bvh in the test data downloaded from download_test.sh, but we cannot process the model_ang.npy for any extra data by using prepreocess.py.
May you provide a preprocessing program used in preprocess test data?
It would be really helpful for us. Thank you.

**Comment by rubenvillegas** [comment]
We don’t use the *_ang.npy data. You can safely comment out that part of
the code. Please let me know if that works.
