### ISSUE TITLE
The download_test.sh (test.tar.gz) from UMich box has been removed

### ISSUE THREAD

**Issue by VinceLiam** [rubenvillegas/cvpr2018nkn#12]
Thanks for your great work! I am currently studying this project but encountered a download problem. I also looked at other issues that others might have the same issue with me. However. it was about a year ago on 25 April 2019. Could you please check the link again? Thanks a lot!

**Comment by rubenvillegas** [comment]
I was able to recover the files and move them to google drive: https://drive.google.com/drive/u/0/folders/1zvPJtW3LyJoIYnU3uVVA9hcOfJKrPqZ0
