### ISSUE TITLE
Questions about the visualization code

### ISSUE THREAD

**Issue by Walter0807** [rubenvillegas/cvpr2018nkn#13]
Thanks for your awesome work cvpr2018nkn! I have some questions about the visualization code, and your kind help is very much appreciated.

First, I realized that you create a separate .blend file for each motion, and I wonder what’s the difference between two .blend files with same from/to characters. Second, we hope to add more characters for future use, could you please share the script for creating those .blend files? Thank you very much!

**Comment by rubenvillegas** [comment]
I created the .blend files by hand using the Blender GUI. It is possible to automate this process but you need to become familiar with the Blender api.
