### ISSUE TITLE
Is it necessary to train for motion reatarget

### ISSUE THREAD

**Issue by wuxiaolianggit** [rubenvillegas/cvpr2018nkn#15]
The number of bone points is the same, but the proportion is not the same. I can directly copy the displacement and rotation vector of character a to the corresponding node of character B. in this way, the same effect can be achieved without using deep learning. Do you think my understanding is correct? @jimeiyang

**Comment by rubenvillegas** [comment]
If I understand correctly, you may be referring to the "Copy input quaternions and velocities" baseline in Table 1, and in the supplementary video. Please let me know if this is right.

**Comment by wuxiaolianggit** [comment]
Your understanding is correct, but I read your paper and found that the effect of hand reproduction is not very good. How do you think it should be improved? @jimeiyang

**Comment by rubenvillegas** [comment]
You can probably see in the paper that we do not handle full hands. We merely handle the joint named hand which does not include fingers. Therefore, hand is a leave joint and there is nothing really constraining it other than the twist term we use. If you want more accurate hand movements, I assume you would have to handle everything up to the fingers.
