### ISSUE TITLE
First Frame Global Position

### ISSUE THREAD

**Issue by 0aqz0** [rubenvillegas/cvpr2018nkn#21]
Hi!

Thanks for sharing such an impressive job.

I have a question, if the network output is the velocity of the root joint, then where does the position of the first frame come from?

It seems that the initial position of the root joint comes from the ground truth as shown in [test_online_retargeting_mixamo.py](https://github.com/rubenvillegas/cvpr2018nkn/blob/41c2a304484daccdb8f59808c71d9543b38a8559/src/test_online_retargeting_mixamo.py#L171)

```
outputB_bvh[:, :3] = gtanim.positions[:1, 0, :].copy()
wjs, rots = put_in_world_bvh(outputB_bvh.copy(), start_rots)
tjoints[:, 0, :] = wjs[0, :, 0].copy()
```
> [](url)

Looking forward to your kind reply.

**Comment by rubenvillegas** [comment]
Hi,

Sorry for the late reply. In order to compare the retargeted motions, we make sure that the character's root start at the same initial position. Otherwise, we cannot compare the trajectories appropriately.
