### ISSUE TITLE
Any better way to download the FBX file from Mixamo?

### ISSUE THREAD

**Issue by wangsen1312** [rubenvillegas/cvpr2018nkn#3]
Do you know any better way to download the FBX file from the website? should I download it one by one?

**Comment by rubenvillegas** [comment]
Not that I am aware of. We downloaded the fbxs one by one for our project.
We tried to have an easier way to do this by sharing the data we downloaded, but unfortunately, the Mixamo team does not allow us to do this, and they require for people to download it from their website.
