### ISSUE TITLE
The link of test data cannot access

### ISSUE THREAD

**Issue by DetectiveLYJ** [rubenvillegas/cvpr2018nkn#4]
I am trying to download the test data using the command ./datasets/download_test.sh, but the link **https://umich.box.com/shared/static/5q39kgt2ftkfy352rr2lmwuzrhqjxwvy.gz** cannot access. could you please put the test data on the Google drive or Baidu Netdisk? Thank you very much~

**Comment by rubenvillegas** [comment]
I just downloaded it from a network outside of the University of Michigan. It has to be a problem with your connection. I don't plan to put the data anywhere else any time soon since it's not an actual download link problem.

Regards,
Ruben

**Comment by DetectiveLYJ** [comment]
thanks for your help! I find there are some restrictions with my connection. And I change a network environment, the data was downloaded successfully!



------------------ 原始邮件 ------------------
发件人: "Ruben Villegas"<notifications@github.com>; 
发送时间: 2019年4月25日(星期四) 晚上9:40
收件人: "rubenvillegas/cvpr2018nkn"<cvpr2018nkn@noreply.github.com>; 
抄送: "雅劼"<842801256@qq.com>; "Manual"<manual@noreply.github.com>; 
主题: Re: [rubenvillegas/cvpr2018nkn] The link of test data cannot access(#4)




I just downloaded it from a network outside of the University of Michigan. It has to be a problem with your connection. I don't plan to put the data anywhere else any time soon since it's not an actual download link problem.
 
Regards,
 Ruben
