### ISSUE TITLE
Release date of "From human 3D pose estimates to 3D characters"

### ISSUE THREAD

**Issue by yzhq97** [rubenvillegas/cvpr2018nkn#9]
Hi, Thanks for you great work! I've been looking forward to the release of " From human 3D pose estimates to 3D characters" for some interesting applications. Could you please give an approximate estimate of when it will be released?

**Comment by rubenvillegas** [comment]
Thanks for your interest. I have not been able to make the time to get around this code. I can, however, provide the code I have for preprocessing the Human 3.6M data if you send me an email inquiry. Then you would need to simply give this as input to get outputs for animating the characters. I have provided this to others that have been able to replicate these results.

**Comment by rubenvillegas** [comment]
Thanks for your interest in this. I have not been able to make the time to get around this code and will likely not have the time any time soon as I am busy with other projects. I can, however, provide the code I have for preprocessing the Human 3.6M data if you send me an email inquiry. Then you would need to simply give this as input to get outputs for animating the characters. I have provided this to others that have been able to replicate these results.
